name:                     Check cargo deny

on:
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  cargo-deny:
    name:                 Cargo deny
    runs-on:              ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories

    continue-on-error:    ${{ matrix.checks == 'advisories' }}

    steps:
      - name:               Checkout Sources
        uses:               actions/checkout@v2

      - name:               Move Cargo.toml
        run:                |
          cd rust
          cp os-specific-lock/android/Cargo.lock .
          cp signer/android-hack/Cargo.toml signer

      - name:               Run cargo-deny
        uses:               EmbarkStudios/cargo-deny-action@v1
        with:
          command:          --manifest-path=./rust/Cargo.toml check ${{ matrix.checks }}

