name:                     Check cargo deny

on:
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  cargo-deny:
    name:                 Cargo deny
    runs-on:              ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories

    continue-on-error:    ${{ matrix.checks == 'advisories' }}

    steps:
      - uses:             actions/checkout@v2
      - uses:             EmbarkStudios/cargo-deny-action@v1
        run:              |
          cd rust
        with:
          command:        check {{ $matrix.checks }}
